### ISSUE TITLE
AuditDiffer: Include=false does not seem to affect Lists

### ISSUE THREAD

**Issue by pingvinen** [rapidcore/rapidcore#129]
I have hit a case similar to the following...

```csharp
public class MyThing
{
	[Audit(Include=false)]
	public string NotImportant { get; set; }

	[Audit(Include=false)]
	public List<UnimportantThing> TheseShouldNotBeInTheLog { get; set; }
}
```

`NotImportant` is not in the log, so that part works (we also specifically have a unit test proving that), but `TheseShouldNotBeInTheLog` does get included in the log. I expect that it is because we only see the properties of the `UnimportantThing` in the `AuditDiffer` where we actually look at `Include`.

This happens with lists, but I would expect that it also happens with something like `public UnimportantThing IgnoreMe { get; set; }`.

**Comment by IceAndSnow** [comment]
After doing some testing, I have come to the same conclusion.
I tested both assumptions and as expected none of them work as intended.

A solution to this could be to not skip object fields/properties in `RapidCore.Diffing.Internal.StateChangeFinderWorker.SetValue` and then extend the `GetAuditReadyDiff` method by keeping a list of all the breadcrumbs of excluded fields/properties and in the end filter the changes, with something like this:

```
public virtual StateChanges GetAuditReadyDiff(object oldState, object newState)
{
    [...]

    auditChanges.Changes = auditChanges.Changes.Where(change => !ShouldChangeBeIgnored(change)).ToList();
            
    return auditChanges;
}

private bool ShouldChangeBeIgnored(StateChange change)
{
    return ExcludedBreadcrumbs.Any(crumb => change.Breadcrumb.StartsWith(crumb));
}
```

**Comment by IceAndSnow** [comment]
What about `ValueMasker`s? This should also be a problem with those, unless they are only ever ment to work on non-classes.
