### ISSUE TITLE
[migration] pgsql migrations does not seem to work properly with steps

### ISSUE THREAD

**Issue by nover** [rapidcore/rapidcore#149]
QA incident for customer.

The first step of a multi-step migration executed successfully and then something died - when restarting the containers it attempts to run the first step again causing failures as the column already exists and then we're kinda stuck.

**Comment by pingvinen** [comment]
As far as I can see the problem is that `PostgreSqlMigrationStorage` does not actually _load_ the completed steps.

I will get that fixed!
