### ISSUE TITLE
Audit differ stack on `decimals` freak out

### ISSUE THREAD

**Issue by nover** [rapidcore/rapidcore#177]
Diffing two simple decimals makes the diff stack / reflection stack freak out. I guess it's due to some internals of the `decimal` that makes the stack go crazy.

Easy fix is `toString` the decimal before diffing...

**Comment by pingvinen** [comment]
The stack is designed to work with classes with fields and properties - it does not make sense for it to deal with instances of things that do not have properties etc.

I will update the underlying `InstanceTraverser` to block "incorrect" usage and then see if it is possible to do something clever to deal with this kind of situation automatically at the high-level available in the audit stack.
