### ISSUE TITLE
Transitive dependency issue with SSH.NET

### ISSUE THREAD

**Issue by roycornelissen** [rapidcore/rapidcore#189]
Hi, we are using `RapidCore` (via the `Skarp.HubSpotClient` Nuget actually), and we've started running into an issue). Our app runs in a Docker container on Linux (target runtime `linux-x64`), and `dotnet restore` started failing:

![image](https://user-images.githubusercontent.com/641868/151124466-0e7e2999-296e-4186-ab14-670305082614.png)

This is a reproduction where I created an empty .NET 6 application that references `RapidCore`, to isolate the problem. This doesn't happen though when I consume `SSH.NET` directly, only when I reference `RapidCore`.

For now, we "resolved" it by referencing those Nugets with version `4.3.0` directly in our app too, but not sure what will happen at runtime.

**Comment by pingvinen** [comment]
Hi

As far as I can see, you have fallen victim to the dependency in `RapidCore` on `SSH.NET`. We have long had a plan to either kill the feature that uses that dependency or moving the feature to its own package to avoid having the dependency in the core library.

What do you think @nover - kill or move? There is also the option to upgrade SSH.NET, but that will only solve the problem short term and I do not think it should take much work to extract the feature into its own package.

**Comment by nover** [comment]
@pingvinen I think we should kill it. I'm not aware of any projects currently using that specific feature, and if so we'll know soon enough and can provide it as a separate pacakge

**Comment by pingvinen** [comment]
@roycornelissen 

Version `0.27.0` is on its way through the pipelines. This version drops the dependency on `SSH.NET` and should solve your problem :)

**Comment by roycornelissen** [comment]
Awesome!
