### ISSUE TITLE
Exception during instance traversal if recursing on Type

### ISSUE THREAD

**Issue by IceAndSnow** [rapidcore/rapidcore#194]
If traversing an instance of the following class:

```csharp
public class ThingWithTypeAsProperty
{
    public Type TypeProperty => typeof(ThingWithTypeAsProperty);
}
```

An exception will be raised. The type `Type` should therefore be added to the `nonRecursedTypes` in the `InstanceTraverser`.
I.e. 

```csharp
private readonly Dictionary<Type, bool> nonRecursedTypes = new Dictionary<Type, bool>
{
    { typeof(char), true },
    ...
    { typeof(Type), true }
};
```

This is particularly a problem when traversing `record` instances, as these implicitly has a type defined (see https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/records#members-of-a-record-type).
It is therefore not possible to traverse `record` types, as of right now.

**Comment by pingvinen** [comment]
The fix was released as version `0.27.3`.
