### ISSUE TITLE
ObjectMethodInvokeExtensions.Invoke*MethodRecursively fails with null arguments

### ISSUE THREAD

**Issue by pingvinen** [rapidcore/rapidcore#25]
Issue moved from rapidcore/issues#2

The current implementation of `ObjectMethodInvokeExtensions.Invoke*MethodRecursively` fails if you supply `null` as an argument for the method that should be called.

This is due to the underlying call to the `GetMethodRecursively`, which is using an array of the types from the arguments to find the method to call. This however does not support the null arguments as it does not have logic to "guess" the type of the corresponding argument.

The `bugfix/objectmethodinvokeextensions-null-handling` branch contains a commit with tests that show the issue and a commit with some work-in-progress code for an attempted solution (which is basically to use the null arguments as wildcards while going through all methods with the given name.

**Comment by IceAndSnow** [comment]
Would it be silly to simply make another extension method, where the types for the parameters are also provided? Whenever one might supply a null-object for one of the parameters, this extension method should then be used instead.

**Comment by pingvinen** [comment]
> Would it be silly to simply make another extension method, where the types for the parameters are also provided? Whenever one might supply a null-object for one of the parameters, this extension method should then be used instead.

That is already possible, as the consumer could use `GetMethodRecursively` first and then invoke it afterwards.
