### ISSUE TITLE
Spec and implement migration downgrade

### ISSUE THREAD

**Issue by pingvinen** [rapidcore/rapidcore#30]
Moved from rapidcore/issues#14

We know that we want our migration stack to support downgrading, but the question remains as to how it should be used.

Should it always just be 1 migration at a time that is downgraded? That would be annoying for projects where you make multiple migrations per release (which would probably be most real projects).

Should it be something like `downgrade N` where `N` is the number of migrations to go back?

**Comment by nover** [comment]
I do not think that we want downgrades at all, it's very complicated and everywhere I have worked with migrations it was always `move forward` even when issues arose after deploying to prod.

Voting for removing downgrade entirely from the stack in a non-breaking fashion.
