### ISSUE TITLE
Auto-expiry on locks

### ISSUE THREAD

**Issue by pingvinen** [rapidcore/rapidcore#31]
Moved from rapidcore/issues#15

Having locks that expire automatically will enable a system that crashed before unlocking to self-heal, as - given enough time - the lock will become available again.

If/when we do this, we have to consider the impact on `RapidCore.Mongo.Migrations`.

**Comment by nover** [comment]
@pingvinen auto expiry for locks using the Redis stack has already been implemented, which means that the shared interface / api for dealing with locks also contain the required building blocks for "auto expiry".

https://github.com/rapidcore/rapidcore.redis/pull/7

**Comment by pingvinen** [comment]
@nover So actually this issue is ready for closing?

**Comment by nover** [comment]
@pingvinen I guess it is unless you want to add extra handling to the migrators.
