### ISSUE TITLE
Helper for generating paths with the correct path separator

### ISSUE THREAD

**Issue by pingvinen** [rapidcore/rapidcore#33]
Moved from rapidcore/issues#17

We have a few tests now that end up with a lot of string operations to generate a filesystem path that works on all operating systems.

We could add something simple like...

```csharp
namespace RapidCore.IO
{
    public class PathHelper
    {
        public virtual string FixPathSeparator(string inputPath)
        {
            return FixPathSeparator(inputPath, Path.DirectorySeparatorChar.ToString());
        }
        
        public virtual string FixPathSeparator(string inputPath, string separator)
        {
            return inputPath
                .Replace("/", separator)
                .Replace("\\", separator);
        }
    }
}
```

**Comment by nover** [comment]
@pingvinen what is wrong with dotnet's `Path.Combine` ?

**Comment by pingvinen** [comment]
>  what is wrong with dotnet's Path.Combine ?

I no longer remember what triggered this. I do however find it annoying to have to write `Path.Combine("Path","That","I","Already","Know")` rather than `FixPathSeparator("Path/That/I/Already/Know")`.
