### ISSUE TITLE
Move code depending on SSH.NET to its own package

### ISSUE THREAD

**Issue by pingvinen** [rapidcore/rapidcore#34]
The [SSH.NET](https://www.nuget.org/packages/SSH.NET/) project does not follow semantic versioning, which means that when they update their packages, it requires more work than just updating the version we depend on.

See [release notes for 2016.1.0](https://github.com/sshnet/SSH.NET/releases/tag/2016.1.0) as an example. This introduces breaking changes, but they only bump the minor.

If we move SSH.NET dependent code to its own package these changes would only affect people using the ssh stuff.

**Comment by nover** [comment]
@pingvinen I think we should do this - the `core` library of RapidCore should stay as slim and dependency free as possible.

**Comment by pingvinen** [comment]
The dependency and the stack that used it has been removed in #190
