### ISSUE TITLE
Mockable way to handle UTC dates

### ISSUE THREAD

**Issue by pingvinen** [rapidcore/rapidcore#42]
`DateTime.UtcNow` is not mockable and is very annoying to test, so having a provider that can be mocked and injected would be better.

It should be named etc. to allow for further additions later on.

**Comment by nover** [comment]
@pingvinen `IDateTimeProvider` ?

**Comment by pingvinen** [comment]
@nover I was thinking more along the lines of `UtcHelper` to communicate that this is all about UTC and "helper" to communicate that it does other things than just providing you with a DateTime instance.
