### ISSUE TITLE
Get documentation stack up and running

### ISSUE THREAD

**Issue by pingvinen** [rapidcore/rapidcore#45]
Our current documentation stack seem to have died and it was always a bit of hassle to use, so let us instead look at some other ones.

The primary candidates are:

[MkDocs](http://www.mkdocs.org/) (using Markdown).

[ReadTheDocs](https://readthedocs.org/) (using reStructuredText, as the Markdown support is very poor).

The keys for us are:
- documentation lives in _our_ repository, so it can easily be managed as part of pull requests
- documentation is easy to write
  - (nice-to-have) can be built locally so stuff can be verified _before_ pushing

**Comment by nover** [comment]
Fixed in #46
